const express=require('express'),http=require('http'),path=require('path'),fs=require('fs'),crypto=require('crypto');
const {Server}=require('socket.io'); const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:'*'}}); const PORT=process.env.PORT||3000;
app.use(express.static(path.join(__dirname,'public')));
const words=JSON.parse(fs.readFileSync(path.join(__dirname,'data/words.json'))),questions=JSON.parse(fs.readFileSync(path.join(__dirname,'data/questions.json'))),truth=JSON.parse(fs.readFileSync(path.join(__dirname,'data/truth.json')));
const rooms=new Map(), AV=['🦊','🐼','🐯','🐸','🐧','🐰','🐻','🐨','🦁','🐵','🐙','🦄','🐲','👻','🤖','🥷','🧙','🧛','🧑‍🚀','🕵️','🐺','🦖','🐱','🐶'];
const code=()=>{let c;do{c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789'.split('').sort(()=>Math.random()-.5).slice(0,5).join('')}while(rooms.has(c));return c},uid=()=>crypto.randomUUID(),clean=x=>String(x||'').trim().replace(/[<>]/g,'').slice(0,12)||'플레이어',active=r=>r.players.filter(p=>p.connected),by=(r,id)=>r.players.find(p=>p.id===id),sock=p=>io.sockets.sockets.get(p.socketId),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const limits={liar:[3,10],mafia:[5,12],truth:[2,30],sabotage:[3,10]};
function pub(r){return {code:r.code,hostId:r.hostId,game:r.game,mode:r.mode,phase:r.phase,round:r.round,players:r.players.map(p=>({id:p.id,name:p.name,avatar:p.avatar,connected:p.connected,score:p.score,alive:p.alive,rolePublic:p.rolePublic})),settings:r.settings,deadline:r.deadline,submitted:r.submitted||[],answersRevealed:r.answersRevealed,answers:r.answersRevealed?r.answers:{},votesSubmitted:r.votesSubmitted||[],voteResult:r.voteResult,truthTurnId:r.truthTurnId,truthQuestion:r.truthQuestion,mafiaLog:r.mafiaLog||[],nightSubmitted:r.nightSubmitted||[],sab:r.game==='sabotage'?r.sab:null,promptMeta:r.game==='liar'&&r.prompt?{category:r.prompt.category,min:r.prompt.min,max:r.prompt.max}:null}}
function emit(r){io.to(r.code).emit('roomState',pub(r));for(const p of r.players){let s=sock(p);if(!s)continue;if(r.game==='liar'&&r.prompt&&r.phase!=='lobby'){let liar=r.liarIds.includes(p.id);s.emit('privateData',{game:'liar',isLiar:liar,word:!liar&&r.mode==='normal'?r.prompt.word:null,category:r.mode==='normal'?r.prompt.category:null,question:!liar&&r.mode==='question'?r.prompt.question:null,min:r.prompt.min,max:r.prompt.max,canGuess:r.phase==='liarGuess'&&r.guessingLiarId===p.id,wordLength:r.phase==='liarGuess'&&r.guessingLiarId===p.id?[...r.prompt.word.replace(/\s/g,'')].length:null})}if(r.game==='mafia'&&r.phase!=='lobby')s.emit('privateData',{game:'mafia',role:p.role,alive:p.alive,mafiaNames:r.players.filter(x=>x.role==='mafia').map(x=>x.name)});if(r.game==='sabotage'&&r.phase!=='lobby')s.emit('privateData',{game:'sabotage',role:p.role,hand:p.hand||[]})}}
function clearT(r){if(r.timer)clearTimeout(r.timer);r.timer=null;r.deadline=null} function timer(r,sec,fn){clearT(r);if(!sec)return;r.deadline=Date.now()+sec*1000;r.timer=setTimeout(()=>{r.timer=null;r.deadline=null;fn()},sec*1000)}
function bind(s,r,p){p.socketId=s.id;p.connected=true;s.join(r.code);s.data.roomCode=r.code;s.data.playerId=p.id} function player(name,avatar,sid){return{id:uid(),sessionId:sid,name:clean(name),avatar:AV.includes(avatar)?avatar:AV[0],connected:true,score:0,alive:true}}
function reset(r){clearT(r);r.submitted=[];r.answers={};r.answersRevealed=false;r.votes={};r.votesSubmitted=[];r.voteResult=null;r.nightActions={};r.nightSubmitted=[]}
function startLiar(r){if(active(r).length<3)throw Error('라이어게임은 최소 3명입니다.');reset(r);r.round++;r.phase='play';let n=clamp(r.settings.liarCount,1,Math.min(3,active(r).length-1));r.liarIds=[...active(r)].sort(()=>Math.random()-.5).slice(0,n).map(p=>p.id);let pool=r.mode==='question'?questions:words;r.prompt=pool[Math.floor(Math.random()*pool.length)];if(r.settings.roundTime)timer(r,r.settings.roundTime,()=>r.mode==='question'?revealAnswers(r):openVote(r));emit(r)}
function revealAnswers(r){if(r.game!=='liar'||r.mode!=='question'||r.phase!=='play')return;for(const p of active(r))if(r.answers[p.id]===undefined)r.answers[p.id]=null;r.answersRevealed=true;r.phase='reveal';if(r.settings.roundTime)timer(r,r.settings.roundTime,()=>openVote(r));emit(r)}
function openVote(r){clearT(r);r.phase='vote';r.votes={};r.votesSubmitted=[];timer(r,r.settings.voteTime||30,()=>tallyLiar(r));emit(r)}
function tallyLiar(r){if(r.phase!=='vote')return;clearT(r);let c={};Object.values(r.votes).forEach(x=>c[x]=(c[x]||0)+1);let m=Math.max(0,...Object.values(c)),top=Object.keys(c).filter(x=>c[x]===m&&m);let target=top.length===1?top[0]:null,caught=target&&r.liarIds.includes(target);r.voteResult={counts:c,targetId:target,liarIds:r.liarIds,caught,tie:top.length!==1};if(caught&&r.mode==='normal'&&r.settings.liarFinalGuess){r.phase='liarGuess';r.guessingLiarId=target;timer(r,25,()=>{r.guessResult={attempted:false,answer:r.prompt.word};r.phase='result';emit(r)});emit(r)}else{r.phase='result';emit(r)}}
function startTruth(r){if(active(r).length<2)throw Error('진실게임은 최소 2명입니다.');reset(r);r.round++;r.phase='truth';r.truthIndex=(r.truthIndex??-1)+1;if(r.truthIndex>=r.players.length)r.truthIndex=0;let p=r.players[r.truthIndex];while(!p.connected){r.truthIndex=(r.truthIndex+1)%r.players.length;p=r.players[r.truthIndex]}r.truthTurnId=p.id;makeTruth(r);emit(r)}
function makeTruth(r){let level=r.settings.truthLevel||'normal', targeted=active(r).length>2&&Math.random()<.35;let pool=targeted?truth.targeted[level]:truth[level],q=pool[Math.floor(Math.random()*pool.length)];if(targeted){let targets=active(r).filter(x=>x.id!==r.truthTurnId),t=targets[Math.floor(Math.random()*targets.length)];q=q.replaceAll('{target}',t.name)}r.truthQuestion=q}
function mafiaSetup(r){if(active(r).length<5)throw Error('마피아게임은 최소 5명입니다.');reset(r);r.round=1;r.players.forEach(p=>{p.alive=true;p.rolePublic=null});let ps=[...active(r)].sort(()=>Math.random()-.5),mc=ps.length>=8?2:1;ps.forEach((p,i)=>p.role=i<mc?'mafia':i===mc?'police':i===mc+1?'doctor':'citizen');r.mafiaLog=[];r.day=1;startMafiaNight(r)}
function startMafiaNight(r){reset(r);r.phase='mafiaNight';r.mafiaLog.push(`🌙 ${r.day}일차 밤이 되었습니다.`);timer(r,r.settings.roundTime||60,()=>resolveNight(r));emit(r)}
function resolveNight(r){if(r.phase!=='mafiaNight')return;clearT(r);let acts=Object.values(r.nightActions),kills=acts.filter(a=>a.type==='kill').map(a=>a.target),save=acts.find(a=>a.type==='save')?.target;let victim=null;if(kills.length){let counts={};kills.forEach(x=>counts[x]=(counts[x]||0)+1);victim=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0]}if(victim&&victim!==save){let p=by(r,victim);if(p){p.alive=false;r.mafiaLog.push(`☀️ 아침이 밝았습니다. ${p.name}님이 밤에 탈락했습니다.`)}}else r.mafiaLog.push('☀️ 아침이 밝았습니다. 지난밤 아무도 탈락하지 않았습니다.');if(checkMafiaEnd(r))return;r.phase='mafiaDay';timer(r,r.settings.roundTime||120,()=>startMafiaVote(r));emit(r)}
function startMafiaVote(r){clearT(r);r.phase='mafiaVote';r.votes={};r.votesSubmitted=[];timer(r,r.settings.voteTime||30,()=>resolveMafiaVote(r));emit(r)}
function resolveMafiaVote(r){if(r.phase!=='mafiaVote')return;clearT(r);let c={};Object.values(r.votes).forEach(x=>c[x]=(c[x]||0)+1),m=Math.max(0,...Object.values(c)),top=Object.keys(c).filter(x=>c[x]===m&&m);if(top.length===1){let p=by(r,top[0]);p.alive=false;p.rolePublic=p.role;r.mafiaLog.push(`⚖️ 투표로 ${p.name}님이 탈락했습니다. 역할: ${roleName(p.role)}`)}else r.mafiaLog.push('⚖️ 투표가 동률이라 아무도 탈락하지 않았습니다.');if(checkMafiaEnd(r))return;r.day++;startMafiaNight(r)}
function roleName(x){return {mafia:'마피아',police:'경찰',doctor:'의사',citizen:'시민'}[x]||x} function checkMafiaEnd(r){let alive=r.players.filter(p=>p.alive),m=alive.filter(p=>p.role==='mafia').length,c=alive.length-m;if(m===0||m>=c){r.phase='mafiaResult';r.mafiaWinner=m===0?'시민팀':'마피아팀';r.mafiaLog.push(`🏆 ${r.mafiaWinner} 승리!`);r.players.forEach(p=>p.rolePublic=p.role);emit(r);return true}return false}
const PATHS=['─','│','└','┘','┌','┐','┼','├','┤','┬','┴'];
function sabSetup(r){if(active(r).length<3)throw Error('사보타지는 최소 3명입니다.');reset(r);r.round=1;r.phase='sab';let ps=[...active(r)].sort(()=>Math.random()-.5),sc=ps.length>=7?2:1;ps.forEach((p,i)=>{p.role=i<sc?'saboteur':'miner';p.hand=Array.from({length:5},()=>PATHS[Math.floor(Math.random()*PATHS.length)])});r.sab={turn:0,turnId:r.players[0].id,board:{'0,2':'START','6,0':'?','6,2':'GOLD','6,4':'?'},discard:0,winner:null};emit(r)}
function sabNext(r){let alive=active(r);r.sab.turn=(r.sab.turn+1)%alive.length;r.sab.turnId=alive[r.sab.turn].id;emit(r)}
function canPlace(r,x,y){if(x<0||x>6||y<0||y>4||r.sab.board[`${x},${y}`])return false;return [[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>r.sab.board[`${x+dx},${y+dy}`])}
function newRoom(game,mode,password,p){return{code:code(),hostId:p.id,players:[p],game,mode:mode||'normal',phase:'lobby',round:0,password:String(password||'').slice(0,24),settings:{liarCount:1,roundTime:120,voteTime:30,liarFinalGuess:true,truthLevel:'normal'},submitted:[],answers:{},votes:{},liarIds:[]}}
io.on('connection',s=>{
s.on('createRoom',(d,cb)=>{try{let game=['liar','mafia','truth','sabotage'].includes(d.game)?d.game:'liar',sid=String(d.sessionId||uid()),p=player(d.name,d.avatar,sid),r=newRoom(game,d.mode,d.password,p);rooms.set(r.code,r);bind(s,r,p);cb?.({ok:true,code:r.code,playerId:p.id,sessionId:sid});emit(r)}catch(e){cb?.({ok:false,error:e.message})}});
s.on('joinRoom',(d,cb)=>{try{let r=rooms.get(String(d.code||'').toUpperCase());if(!r)throw Error('방을 찾을 수 없습니다.');if(r.password&&r.password!==String(d.password||''))throw Error('비밀번호가 올바르지 않습니다.');let sid=String(d.sessionId||uid()),old=r.players.find(p=>p.sessionId===sid);if(old){bind(s,r,old);cb?.({ok:true,code:r.code,playerId:old.id,sessionId:sid});emit(r);return}let lim=limits[r.game][1];if(r.players.length>=lim)throw Error(`이 게임은 최대 ${lim}명입니다.`);if(r.phase!=='lobby')throw Error('게임 진행 중에는 새로 참가할 수 없습니다.');let p=player(d.name,d.avatar,sid);r.players.push(p);bind(s,r,p);cb?.({ok:true,code:r.code,playerId:p.id,sessionId:sid});emit(r)}catch(e){cb?.({ok:false,error:e.message})}});
s.on('resumeSession',(d,cb)=>{let r=rooms.get(String(d.code||'').toUpperCase()),p=r?.players.find(x=>x.sessionId===d.sessionId);if(!r||!p)return cb?.({ok:false});bind(s,r,p);cb?.({ok:true,code:r.code,playerId:p.id,sessionId:d.sessionId});emit(r)});
s.on('updateSettings',(d,cb)=>{let r=rooms.get(s.data.roomCode);try{if(!r||r.hostId!==s.data.playerId||r.phase!=='lobby')throw Error('방장만 설정할 수 있습니다.');if(d.mode)r.mode=d.mode;if(d.liarCount)r.settings.liarCount=+d.liarCount;if(d.roundTime!==undefined)r.settings.roundTime=+d.roundTime;if(d.voteTime)r.settings.voteTime=+d.voteTime;if(d.truthLevel)r.settings.truthLevel=d.truthLevel;if(d.liarFinalGuess!==undefined)r.settings.liarFinalGuess=!!d.liarFinalGuess;emit(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('startGame',(_,cb)=>{let r=rooms.get(s.data.roomCode);try{if(!r||r.hostId!==s.data.playerId)throw Error('방장만 시작할 수 있습니다.');let min=limits[r.game][0];if(active(r).length<min)throw Error(`${r.game==='mafia'?'마피아':r.game==='truth'?'진실게임':r.game==='sabotage'?'사보타지':'라이어게임'}은 최소 ${min}명입니다.`);if(r.game==='liar')startLiar(r);if(r.game==='truth')startTruth(r);if(r.game==='mafia')mafiaSetup(r);if(r.game==='sabotage')sabSetup(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('submitAnswer',(d,cb)=>{let r=rooms.get(s.data.roomCode),id=s.data.playerId;try{let n=Number(d.value);if(r.game!=='liar'||r.mode!=='question'||r.phase!=='play')throw Error('지금 답변할 수 없습니다.');if(!Number.isFinite(n)||n<r.prompt.min||n>r.prompt.max)throw Error('범위를 확인해주세요.');r.answers[id]=Math.round(n);r.submitted=Object.keys(r.answers);if(active(r).every(p=>r.answers[p.id]!==undefined))revealAnswers(r);else emit(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('openVoting',(_,cb)=>{let r=rooms.get(s.data.roomCode);try{if(r.hostId!==s.data.playerId)throw Error('방장만 가능합니다.');if(r.game==='liar')openVote(r);else if(r.game==='mafia'&&r.phase==='mafiaDay')startMafiaVote(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('vote',(d,cb)=>{let r=rooms.get(s.data.roomCode),id=s.data.playerId;try{if(!['vote','mafiaVote'].includes(r.phase))throw Error('투표 시간이 아닙니다.');if(r.votes[id])throw Error('이미 투표했습니다.');if(id===d.targetId)throw Error('자기 자신은 선택할 수 없습니다.');r.votes[id]=d.targetId;r.votesSubmitted=Object.keys(r.votes);let voters=r.game==='mafia'?active(r).filter(p=>p.alive):active(r);if(voters.every(p=>r.votes[p.id]))r.game==='mafia'?resolveMafiaVote(r):tallyLiar(r);else emit(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('submitLiarGuess',(d,cb)=>{let r=rooms.get(s.data.roomCode);if(r?.phase!=='liarGuess'||r.guessingLiarId!==s.data.playerId)return cb?.({ok:false});let a=r.prompt.word,g=String(d.guess||'').trim(),ok=g.replace(/\s/g,'')===a.replace(/\s/g,'');r.guessResult={attempted:true,correct:ok,guess:g,answer:a};r.phase='result';clearT(r);emit(r);cb?.({ok:true})});
s.on('truthNext',(_,cb)=>{let r=rooms.get(s.data.roomCode);if(!r||r.game!=='truth'||r.hostId!==s.data.playerId)return cb?.({ok:false,error:'방장만 가능합니다.'});startTruth(r);cb?.({ok:true})});s.on('truthReroll',(_,cb)=>{let r=rooms.get(s.data.roomCode);if(!r||r.game!=='truth'||r.hostId!==s.data.playerId)return cb?.({ok:false});makeTruth(r);emit(r);cb?.({ok:true})});
s.on('nightAction',(d,cb)=>{let r=rooms.get(s.data.roomCode),p=by(r,s.data.playerId);try{if(!r||r.phase!=='mafiaNight'||!p.alive)throw Error('행동할 수 없습니다.');let type=p.role==='mafia'?'kill':p.role==='doctor'?'save':p.role==='police'?'inspect':null;if(!type)throw Error('밤 능력이 없습니다.');r.nightActions[p.id]={type,target:d.targetId};r.nightSubmitted=Object.keys(r.nightActions);if(type==='inspect'){let t=by(r,d.targetId);sock(p)?.emit('inspection',{name:t.name,isMafia:t.role==='mafia'})}let actors=active(r).filter(x=>x.alive&&['mafia','doctor','police'].includes(x.role));if(actors.every(x=>r.nightActions[x.id]))resolveNight(r);else emit(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('sabPlace',(d,cb)=>{let r=rooms.get(s.data.roomCode),p=by(r,s.data.playerId);try{if(!r||r.game!=='sabotage'||r.phase!=='sab'||r.sab.turnId!==p.id)throw Error('내 차례가 아닙니다.');let i=+d.index;if(!p.hand[i]||!canPlace(r,+d.x,+d.y))throw Error('그 위치에는 놓을 수 없습니다.');r.sab.board[`${+d.x},${+d.y}`]=p.hand.splice(i,1)[0];p.hand.push(PATHS[Math.floor(Math.random()*PATHS.length)]);if(+d.x===5&&+d.y===2){r.sab.winner='광부팀';r.players.forEach(x=>x.rolePublic=x.role);r.phase='sabResult'}else sabNext(r);emit(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('sabDiscard',(d,cb)=>{let r=rooms.get(s.data.roomCode),p=by(r,s.data.playerId);try{if(r.sab.turnId!==p.id)throw Error('내 차례가 아닙니다.');p.hand.splice(+d.index,1);p.hand.push(PATHS[Math.floor(Math.random()*PATHS.length)]);r.sab.discard++;if(r.sab.discard>=r.players.length*6){r.sab.winner='사보타지팀';r.players.forEach(x=>x.rolePublic=x.role);r.phase='sabResult'}else sabNext(r);emit(r);cb?.({ok:true})}catch(e){cb?.({ok:false,error:e.message})}});
s.on('nextRound',(_,cb)=>{let r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.data.playerId)return cb?.({ok:false});if(r.game==='liar')startLiar(r);else if(r.game==='truth')startTruth(r);else if(r.game==='mafia')mafiaSetup(r);else sabSetup(r);cb?.({ok:true})});
s.on('backToLobby',(_,cb)=>{let r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.data.playerId)return cb?.({ok:false});clearT(r);r.phase='lobby';r.round=0;r.players.forEach(p=>{p.alive=true;p.rolePublic=null});emit(r);cb?.({ok:true})});
s.on('leaveRoom',(_,cb)=>{let r=rooms.get(s.data.roomCode);if(r){r.players=r.players.filter(p=>p.id!==s.data.playerId);if(!r.players.length)rooms.delete(r.code);else{if(r.hostId===s.data.playerId)r.hostId=r.players[0].id;emit(r)}}cb?.({ok:true})});
s.on('disconnect',()=>{let r=rooms.get(s.data.roomCode),p=r&&by(r,s.data.playerId);if(p){p.connected=false;p.socketId=null;emit(r)}})
});
app.get('/health',(_,res)=>res.json({ok:true,version:'5.0.0',rooms:rooms.size}));server.listen(PORT,()=>console.log('Soso Party Game v5 on',PORT));
